# Generated by Django 3.2 on 2023-04-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20230423_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Amethyst', 'Amethyst'), ('Calcite', 'Calcite'), ('Quartz', 'Quartz')], default='Quartz', max_length=10),
        ),
    ]
