# Generated by Django 3.2 on 2023-04-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20230423_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='friendly_name',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Amethyst', 'Amethyst'), ('Calcite', 'Calcite'), ('Quartz', 'Quartz')], default='Quartz', max_length=10),
        ),
    ]
