# Generated by Django 3.2 on 2023-04-25 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20230423_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rating',
            new_name='rated',
        ),
    ]
