# Generated by Django 3.2 on 2023-04-25 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_rename_rating_review_rated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rated',
            new_name='rating',
        ),
    ]
