# Generated by Django 3.2 on 2023-05-04 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_rename_rated_review_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
